### PR TITLE
parseIfStatement: enforce matching block types in clauses

### PR DESCRIPTION
**Pull request by wcjohnson**
- Added a check in `parseIfStatement` — look down the tree to the consequent and check its block type.
- All extant tests pass.
- Added new test fixtures for mismatching block types.

### CODE REVIEW

**Comment by wcjohnson** [comment]
Hold off on merging this, there are inconsistencies with `IfExpression` as I thought there might be. Might as well get them ironed out. I will message you on gitter.

**Comment by rattrayalex** [comment]
I haven't tried running/testing yet, but some ideas up at https://github.com/lightscript/babylon-lightscript/pull/4

**Comment by wcjohnson** [comment]
@rattrayalex 

I implemented the patch in #4 and ran the test suite. Several failures:

`if-expression/block-then-oneline`:
```
x = if false:
  1
elif true: 2
```
Expected to pass, fails with:
```
Error: lightscript/if-expression/block-then-oneline/actual.js: Unexpected token (1:12)
```

`if-expression/elif`
```
x = if false:
  1
elif true:
  2
```
Expected to pass, fails with:
```
Error: lightscript/if-expression/elif/actual.js: Unexpected token (1:12)
```

Same failure for `if-expression/else if` amd `if-expression/no alternate`... It looks like it's just not taking colons at all?

Also, one strange failure outside the lightscript test suite:
```
Error: /Users/wcj/dev/node_modules/babylon-lightscript/test/fixtures/es2015/uncategorised/273/actual.js: Expected error message: Unexpected token, expected : (1:16). But parsing succeeded.
```
Why is that even calling the lightscript plugin?

**Comment by rattrayalex** [comment]
Ah, womp... see my comments in gitter, proposed something that may be simpler / more flexible there

Regarding outside-of-lightscript suite, yes, they're all run with the `lightscript` plugin enabled. This helps catch backwards-incompatibilities. The cases where they're intended/accepted, I add a second `expected.lightscript.json` or `options.lightscript.json` as a sibling, which acts as a spec/documentation of all backwards-incompatibilities

**Comment by wcjohnson** [comment]
Withdrawing this PR. Will separate into two phases:
- I'm going to push a clean PR covering `IfStatement`s only using ideas from your #4. This PR passes all tests including some new ones I added, and I believe it's correct and can be merged right away.
- Work on `IfExpression`s will be a separate PR.

**Comment by rattrayalex** [comment]
@wcjohnson actually, I'm not so sure about the approach in #4 ...

**Pull request closed without merging**
