### PR TITLE
Parsing: made parenthesis optional on lambda-expressions with no params

### PR DESCRIPTION
**Pull request by wcjohnson**
- Added arrows as valid tokens to start an expression.

### CODE REVIEW

**Comment by rattrayalex** [comment]
Let's keep tests to one thing per file; and some of these tests aren't necessary. Maybe these:

`no-parens/actual.js`:
```
-> 1
```

`no-parens-assign/actual.js`:
```
x = => 1
```

`no-parens-call/actual.js`:
```
f(a
  => 1
)
```
I'm happy to make these changes if you like

**Comment by wcjohnson** [comment]
Updated as requested.

**Review by rattrayalex — APPROVED** [review]
Awesome!

**Comment by rattrayalex** [comment]
Congrats on shipping the first PR to lightscript, @wcjohnson !

**Pull request merged**
