### PR TITLE
Try blocks aligned

### PR DESCRIPTION
**Pull request by rattrayalex**
Addresses https://github.com/lightscript/lightscript/issues/23
cc @wcjohnson

### CODE REVIEW

**Comment by rattrayalex** [comment]
The `blockType` wasn't needed for this (or do-while, which already has a matching-indent requirement) so I removed it, FYI. 

However, I think that's because I'd forgotten that I'd won the battle not to enforce matching `:`/`{` in `if`s, and added that requirement in `try`/`catch`, which is inconsistent. So I may need to rethink that.

**Comment by wcjohnson** [comment]
If you are willing to enforce syntax with `if` as well, you might not need the stack at all.

**Comment by rattrayalex** [comment]
Yeah. I'm finally starting to lean that direction 😉 

As you know, the thinking behind the flexibility is that the linter should enforce consistency, and the compiler permit poor style, so that while a developer is quickly iterating on code they can proceed with mismatched style and then fix it up later. 

However, we don't currently have lsc-specific linting rules, and it's now looking like that might be a ways out. 

So while there will probably be other language features that are permissive in the hopes of a future linter coming to the rescue, I think it might be worth just enforcing consistency at the compiler level for now, and possibly reimplementing the current behavior later. 

@wcjohnson it sounds like you'd be in favor of that (you always wanted consistency enforced here anyway, IIRC) – @citycide any thoughts on this?

**Comment by rattrayalex** [comment]
Actually, the stack looks necessary in cases like this anyway: 

```js
x = if a:
  if (b) {
    c
  }
else if d:
  e
```

where, when parsing the inner `if`, the `else` is encountered, and cannot be discarded until after the alternate if's condition (`d`) is parsed, and the `:` is seen. That could be done with an extensive lookahead, but it would be quite messy as it traverses a few methods (plus would be slower).

**Comment by wcjohnson** [comment]
That case can be handled by passing an `isWhiteBlock` parameter along the `parseIf` chain. I had working code for this at one point.

**Comment by rattrayalex** [comment]
I'll give that a try, thanks

**Comment by rattrayalex** [comment]
Err, sorry, @wcjohnson at a high level can you explain how you handled the lookahead problem there?

**Comment by wcjohnson** [comment]
The approach I outlined probably won't work; I thought about it some more and deleted the comment. I do think it can be done without lookahead but it wouldn't be that straightforward.

**Comment by rattrayalex** [comment]
Hmm, k. I think I'll continue to use the stack but might still enforce `:` consistency.

**Comment by rattrayalex** [comment]
(FYI, I have to head out for the day soon and likely won't finish before then)

**Comment by rattrayalex** [comment]
Updated, now enforces matching `:` behavior in both `if` and `try`

**Comment by rattrayalex** [comment]
Will merge tomorrow unless anyone has concerns

**Comment by wcjohnson** [comment]
I think this is the right way to go, no objections here.

**Pull request merged**
